name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello World!"
          echo "Welcome to Github Actions!"
      - name: Print Good Bye
        run: echo "Done - Bye!"
